#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using SbdefGen.Core;
using SbdefGen.Core.Ast;

namespace SbdefGen.Core.Emitters;

/// <summary>
/// v0.2 Emitter：从 SbdefFile 生成两份 C# 代码。
/// <list type="bullet">
/// <item>UActionPortIds.{Segment}.cs — PropertyKey&lt;T&gt; 类型化端口键</item>
/// <item>ActionDefs.{Segment}.cs     — IActionDefinitionProvider 完整实现</item>
/// </list>
/// </summary>
internal static class SbdefDefEmitter
{
    public static Dictionary<string, string> Emit(
        SbdefFile ast, string sourceName,
        Dictionary<string, EnumDecl>? globalEnumRegistry = null,
        Dictionary<string, string>? markerBaseTypeRegistry = null,
        bool emitActionDefinitions = true)
    {
        var actions = ast.Statements.OfType<ActionDecl>().ToList();
        if (actions.Count == 0)
            return new Dictionary<string, string>();

        var groups = actions
            .GroupBy(a => FirstSegment(a.TypeId))
            .ToList();

        var result = new Dictionary<string, string>();
        foreach (var grp in groups)
        {
            var ns     = grp.Key;
            var pascal = SbdefActionEmitter.ToPascalSegment(ns);
            var list   = grp.ToList();

            result[$"UActionPortIds.{pascal}.cs"] = EmitPortIds(list, pascal, sourceName);
            if (emitActionDefinitions)
            {
                result[$"ActionDefs.{pascal}.cs"] = EmitActionDefs(list, pascal, sourceName, globalEnumRegistry, markerBaseTypeRegistry);
            }
        }
        return result;
    }

    // ── UActionPortIds 生成 ──────────────────────────────────

    private static string EmitPortIds(
        List<ActionDecl> actions, string segmentPascal, string sourceName)
    {
        var bodySb = new StringBuilder();
        foreach (var action in actions)
        {
            var className = TypeIdToClassName(action.TypeId);
            bodySb.AppendLine($"        public static class {className}");
            bodySb.AppendLine( "        {");
            bodySb.AppendLine( "            public const string In  = \"in\";");
            bodySb.AppendLine( "            public const string Out = \"out\";");

            if (action.Fields != null)
            {
                foreach (var field in action.Fields)
                {
                    var fieldName  = field.Name;
                    var keyString  = SbdefNameUtility.ToCamel(field.Name);
                    var csharpType = FieldTypeToCSharp(field.TypeName);
                    bodySb.AppendLine($"            public static readonly PropertyKey<{csharpType}> {fieldName} = new(\"{keyString}\");");
                }
            }

            foreach (var port in action.Ports)
            {
                var fieldName  = port.PortName;
                var keyString  = SbdefNameUtility.ToCamel(port.PortName);
                var csharpType = PortTypeToCSharp(port.TypeName);
                bodySb.AppendLine($"            public static readonly PropertyKey<{csharpType}> {fieldName} = new(\"{keyString}\");");
            }

            foreach (var fp in action.FlowPorts)
            {
                var keyString = SbdefNameUtility.ToCamel(fp.PortName);
                bodySb.AppendLine($"            public const string {fp.PortName} = \"{keyString}\";");
            }

            bodySb.AppendLine("        }");
            bodySb.AppendLine();
        }

        var body = bodySb.ToString();
        return $$"""
// <auto-generated>
// 由 SbdefCodegen 从 {{sourceName}}.sbdef 生成，请勿手动修改。
// </auto-generated>
#nullable enable
using SceneBlueprint.Core;

namespace SceneBlueprintUser.Generated
{
    public static partial class UActionPortIds
    {
{{body}}    }
}

""";
    }

    // ── ActionDefs 生成 ──────────────────────────────────────

    private static string EmitActionDefs(
        List<ActionDecl> actions, string segmentPascal, string sourceName,
        Dictionary<string, EnumDecl>? globalEnumRegistry = null,
        Dictionary<string, string>? markerBaseTypeRegistry = null)
    {
        var sb = new StringBuilder();

        foreach (var action in actions)
        {
            var className  = TypeIdToClassName(action.TypeId); // VFXCameraShake
            var defClass   = className + "Def";                 // VFXCameraShakeDef
            var uatRef     = TypeIdToUatRef(action.TypeId);    // UAT.Vfx.CameraShake
            var meta       = action.Meta;

            sb.AppendLine($"    [ActionType({uatRef})]");
            sb.AppendLine($"    public class {defClass} : IActionDefinitionProvider");
            sb.AppendLine("    {");
            sb.AppendLine("        public ActionDefinition Define() => new ActionDefinition");
            sb.AppendLine("        {");
            sb.AppendLine($"            TypeId      = {uatRef},");

            // DisplayName：有则用，无则用 TypeId 末段
            var displayName = meta.DisplayName ?? LastSegment(action.TypeId);
            sb.AppendLine($"            DisplayName = \"{EscapeString(displayName)}\",");

            if (!string.IsNullOrEmpty(meta.Category))
                sb.AppendLine($"            Category    = \"{EscapeString(meta.Category!)}\",");

            if (!string.IsNullOrEmpty(meta.Description))
                sb.AppendLine($"            Description = \"{EscapeString(meta.Description!)}\",");

            if (!string.IsNullOrEmpty(meta.ThemeColor))
            {
                var color = ParseThemeColor(meta.ThemeColor!);
                if (color != null)
                    sb.AppendLine($"            ThemeColor  = new Color4({color}),");
            }

            var duration = ParseDuration(meta.Duration);
            sb.AppendLine($"            Duration    = {duration},");

            // Ports
            sb.AppendLine("            Ports = new[]");
            sb.AppendLine("            {");
            sb.AppendLine($"                Port.In(UActionPortIds.{className}.In,  \"输入\"),");
            sb.AppendLine($"                Port.Out(UActionPortIds.{className}.Out, \"输出\"),");
            foreach (var fp in action.FlowPorts)
            {
                var portLabel = fp.Label ?? fp.PortName;
                var portFactory = fp.IsInput ? "Port.InMulti" : "Port.Out";
                sb.AppendLine($"                {portFactory}(UActionPortIds.{className}.{fp.PortName}, \"{EscapeString(portLabel)}\"),");
            }
            // 数据端口（outport / inport）
            foreach (var port in action.Ports)
            {
                if (port.DataDirection == null) continue;
                var pLabel   = port.Label ?? port.PortName;
                var pKeyRef  = $"UActionPortIds.{className}.{port.PortName}";
                var pDataType = port.TypeName; // "int", "float", "string", "bool"
                if (port.DataDirection == "out")
                    sb.AppendLine($"                Port.DataOut({pKeyRef}, \"{EscapeString(pLabel)}\", \"{pDataType}\"),");
                else
                    sb.AppendLine($"                Port.DataIn({pKeyRef}, \"{EscapeString(pLabel)}\", \"{pDataType}\"),");
            }
            sb.AppendLine("            },");

            // Properties — 从 action.Fields 生成（field 声明）
            var fields = action.Fields;
            if (fields != null && fields.Count > 0)
            {
                sb.AppendLine("            Properties = new[]");
                sb.AppendLine("            {");
                int order = 0;
                foreach (var field in fields)
                {
                    var propLine = BuildFieldPropLine(className, field, order++, globalEnumRegistry, markerBaseTypeRegistry);
                    sb.AppendLine($"                {propLine}");
                }
                sb.AppendLine("            },");
            }
            else
            {
                sb.AppendLine("            Properties = System.Array.Empty<PropertyDefinition>(),");
            }

            // SceneRequirements — 不再显式赋值，由 ActionDefinition 从 Properties 中自动推导
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        var body = sb.ToString();
        return $$"""
// <auto-generated>
// 由 SbdefCodegen 从 {{sourceName}}.sbdef 生成，请勿手动修改。
// </auto-generated>
#nullable enable
using NodeGraph.Math;
using SceneBlueprint.Contract;
using SceneBlueprint.Core;

namespace SceneBlueprintUser.Generated
{
{{body}}}

""";
    }

    // ── 辅助：生成单条 Prop.* 调用 ──────────────────────────

    private static string BuildPropLine(string className, PortDecl port, int order)
    {
        var keyRef   = $"UActionPortIds.{className}.{port.PortName}";
        var label    = port.Label ?? port.PortName;
        var labelLit = $"\"{EscapeString(label)}\"";
        var typeName = port.TypeName.ToLower();

        // sceneref(Area/Point) → Prop.SceneBinding
        if (typeName == "sceneref")
        {
            var bindingType = port.SceneRefType ?? "Transform";
            return $"Prop.SceneBinding({keyRef}, {labelLit}, BindingType.{bindingType}, order: {order}),";
        }

        // list → Prop.StructList
        if (typeName == "list")
        {
            var summary = port.Summary != null ? $"\"{EscapeString(port.Summary)}\"" : "null";
            if (port.NestedPortFields != null && port.NestedPortFields.Count > 0)
            {
                var fieldLines = new System.Text.StringBuilder();
                foreach (var f in port.NestedPortFields)
                {
                    var fLabel = f.Label ?? f.Name;
                    var fKey   = SbdefNameUtility.ToCamel(f.Name);
                    fieldLines.Append(BuildNestedFieldProp(fKey, fLabel, f.TypeName, f.EnumValues));
                    fieldLines.Append(", ");
                }
                return $"Prop.StructList({keyRef}, {labelLit}, new PropertyDefinition[] {{ {fieldLines}}}, summaryFormat: {summary}, order: {order}),";
            }
            return $"Prop.StructList({keyRef}, {labelLit}, System.Array.Empty<PropertyDefinition>(), summaryFormat: {summary}, order: {order}),";
        }

        var defaultVal = port.DefaultValue;
        var min        = port.Min;
        var max        = port.Max;

        switch (typeName)
        {
            case "float":
            {
                var def  = FormatFloat(defaultVal ?? "0");
                var args = $"{keyRef}, {labelLit}, defaultValue: {def}";
                if (min != null) args += $", min: {FormatFloat(min)}";
                if (max != null) args += $", max: {FormatFloat(max)}";
                args += $", order: {order}";
                return $"Prop.Float({args}),";
            }
            case "int":
            {
                var def  = FormatInt(defaultVal ?? "0");
                var args = $"{keyRef}, {labelLit}, defaultValue: {def}";
                if (min != null) args += $", min: {FormatInt(min)}";
                if (max != null) args += $", max: {FormatInt(max)}";
                args += $", order: {order}";
                return $"Prop.Int({args}),";
            }
            case "bool":
            {
                var def = (defaultVal ?? "false").ToLower();
                return $"Prop.Bool({keyRef}, {labelLit}, defaultValue: {def}, order: {order}),";
            }
            default: // string 或其他类型
            {
                var def = defaultVal != null ? $"\"{EscapeString(defaultVal)}\"" : "\"\"";
                return $"Prop.String({keyRef}, {labelLit}, defaultValue: {def}, order: {order}),";
            }
        }
    }

    /// <summary>为 StructList 嵌套字段生成 Prop.* 调用片段（不含尾部逗号）</summary>
    private static string BuildNestedFieldProp(string camelKey, string label, string typeName,
        System.Collections.Generic.List<string>? enumValues = null)
    {
        var labelLit = $"\"{EscapeString(label)}\"";
        if (typeName.ToLower() == "enum" && enumValues != null && enumValues.Count > 0)
        {
            var opts = string.Join(", ", enumValues.Select(v => $"\"{v}\""));
            return $"Prop.Enum(\"{camelKey}\", {labelLit}, new[] {{ {opts} }})";
        }
        return typeName.ToLower() switch
        {
            "float"  => $"Prop.Float(\"{camelKey}\", {labelLit})",
            "int"    => $"Prop.Int(\"{camelKey}\", {labelLit})",
            "bool"   => $"Prop.Bool(\"{camelKey}\", {labelLit})",
            _        => $"Prop.String(\"{camelKey}\", {labelLit})",
        };
    }

    // ── 辅助：从 FieldDecl 生成单条 Prop.* 调用（action 级 field 声明） ──

    private static string BuildFieldPropLine(string className, FieldDecl field, int order,
        Dictionary<string, EnumDecl>? globalEnumRegistry = null,
        Dictionary<string, string>? markerBaseTypeRegistry = null)
    {
        var keyRef   = $"UActionPortIds.{className}.{field.Name}";
        var label    = field.Label ?? field.Name;
        var labelLit = $"\"{EscapeString(label)}\"";
        var typeName = field.TypeName.ToLower();

        // sceneref(WaveSpawnArea/TriggerZone/Area/Point) → Prop.SceneBinding（可选带 MarkerRequirement）
        if (typeName == "sceneref")
        {
            var markerTypeId = field.SceneRefType ?? "Transform";
            // 解析 BindingType 枚举值：具体子类型 → 基类（如 WaveSpawnArea → Area）
            var bindingTypeEnum = ResolveBindingType(markerTypeId, markerBaseTypeRegistry);
            var hasConstraint = field.IsRequired || field.IsExclusive ||
                                (field.RequiredAnnotations != null && field.RequiredAnnotations.Count > 0);
            if (hasConstraint)
            {
                var bindingKey = SbdefNameUtility.ToCamel(field.Name);
                var reqParts = new List<string>();
                reqParts.Add($"\"{bindingKey}\"");
                reqParts.Add($"\"{markerTypeId}\"");
                if (field.IsRequired) reqParts.Add("required: true");
                if (field.IsExclusive) reqParts.Add("exclusive: true");
                if (field.RequiredAnnotations != null && field.RequiredAnnotations.Count > 0)
                {
                    var annos = string.Join(", ", field.RequiredAnnotations.Select(a => $"\"{EscapeString(a)}\""));
                    reqParts.Add($"requiredAnnotations: new[] {{ {annos} }}");
                }
                reqParts.Add($"displayName: {labelLit}");
                var reqExpr = $"new MarkerRequirement({string.Join(", ", reqParts)})";
                return $"Prop.SceneBinding({keyRef}, {labelLit}, BindingType.{bindingTypeEnum}, requirement: {reqExpr}, order: {order}),";
            }
            return $"Prop.SceneBinding({keyRef}, {labelLit}, BindingType.{bindingTypeEnum}, order: {order}),";
        }

        // list → Prop.StructList
        if (typeName == "list")
        {
            var summary = field.Summary != null ? $"\"{EscapeString(field.Summary)}\"" : "null";
            if (field.NestedFields != null && field.NestedFields.Count > 0)
            {
                var fieldLines = new System.Text.StringBuilder();
                foreach (var f in field.NestedFields)
                {
                    var fLabel = f.Label ?? f.Name;
                    var fKey   = SbdefNameUtility.ToCamel(f.Name);
                    // 嵌套字段中的 enum(Name) 引用：查找公共枚举值
                    List<string>? enumVals = f.EnumValues;
                    if (enumVals == null && f.EnumRef != null && globalEnumRegistry != null &&
                        globalEnumRegistry.TryGetValue(f.EnumRef, out var enumDecl))
                    {
                        enumVals = enumDecl.Values.Select(v => v.Name).ToList();
                    }
                    fieldLines.Append(BuildNestedFieldProp(fKey, fLabel, f.TypeName, enumVals));
                    fieldLines.Append(", ");
                }
                return $"Prop.StructList({keyRef}, {labelLit}, new PropertyDefinition[] {{ {fieldLines}}}, summaryFormat: {summary}, order: {order}),";
            }
            return $"Prop.StructList({keyRef}, {labelLit}, System.Array.Empty<PropertyDefinition>(), summaryFormat: {summary}, order: {order}),";
        }

        // enum → Prop.Enum（内联枚举值或引用公共枚举）
        if (typeName == "enum")
        {
            List<string>? enumVals = field.EnumValues;
            if (enumVals == null && field.EnumRef != null && globalEnumRegistry != null &&
                globalEnumRegistry.TryGetValue(field.EnumRef, out var enumDecl))
            {
                enumVals = enumDecl.Values.Select(v => v.Name).ToList();
            }
            if (enumVals != null && enumVals.Count > 0)
            {
                var opts = string.Join(", ", enumVals.Select(v => $"\"{v}\""));
                return $"Prop.Enum({keyRef}, {labelLit}, new[] {{ {opts} }}, order: {order}),";
            }
            // 无枚举值时降级为 string
            return $"Prop.String({keyRef}, {labelLit}, defaultValue: \"\", order: {order}),";
        }

        var defaultVal = field.DefaultValue;
        var min        = field.Min;
        var max        = field.Max;

        switch (typeName)
        {
            case "float":
            {
                var def  = FormatFloat(defaultVal ?? "0");
                var args = $"{keyRef}, {labelLit}, defaultValue: {def}";
                if (min != null) args += $", min: {FormatFloat(min)}";
                if (max != null) args += $", max: {FormatFloat(max)}";
                args += $", order: {order}";
                return $"Prop.Float({args}),";
            }
            case "int":
            {
                var def  = FormatInt(defaultVal ?? "0");
                var args = $"{keyRef}, {labelLit}, defaultValue: {def}";
                if (min != null) args += $", min: {FormatInt(min)}";
                if (max != null) args += $", max: {FormatInt(max)}";
                args += $", order: {order}";
                return $"Prop.Int({args}),";
            }
            case "bool":
            {
                var def = (defaultVal ?? "false").ToLower();
                return $"Prop.Bool({keyRef}, {labelLit}, defaultValue: {def}, order: {order}),";
            }
            case "signaltag":
            {
                var def = defaultVal != null ? $"\"{EscapeString(defaultVal)}\"" : "\"\"";
                return $"Prop.SignalTagSelector({keyRef}, {labelLit}, defaultValue: {def}, order: {order}),";
            }
            case "entityref":
            {
                var def = defaultVal != null ? $"\"{EscapeString(defaultVal)}\"" : "\"\"";
                return $"Prop.EntityRefSelector({keyRef}, {labelLit}, defaultValue: {def}, order: {order}),";
            }
            case "conditionparams":
            {
                var def = defaultVal != null ? $"\"{EscapeString(defaultVal)}\"" : "\"\"";
                return $"Prop.ConditionParams({keyRef}, {labelLit}, defaultValue: {def}, order: {order}),";
            }
            default: // string 或其他类型
            {
                var def = defaultVal != null ? $"\"{EscapeString(defaultVal)}\"" : "\"\"";
                return $"Prop.String({keyRef}, {labelLit}, defaultValue: {def}, order: {order}),";
            }
        }
    }

    // ── 名称转换工具 ─────────────────────────────────────────

    /// <summary>"VFX.CameraShake" → "VFXCameraShake"（去除 . 连接）</summary>
    private static string TypeIdToClassName(string typeId)
        => typeId.Replace(".", "");

    /// <summary>"VFX.CameraShake" → "UAT.Vfx.CameraShake"</summary>
    private static string TypeIdToUatRef(string typeId)
    {
        var segments = typeId.Split('.');
        if (segments.Length < 2) return $"UAT.{typeId}";
        var ns   = SbdefActionEmitter.ToPascalSegment(segments[0]);
        var name = segments[segments.Length - 1];
        return $"UAT.{ns}.{name}";
    }

    /// <summary>"VFX.CameraShake" → "VFX"</summary>
    private static string FirstSegment(string typeId)
    {
        var dot = typeId.IndexOf('.');
        return dot < 0 ? typeId : typeId.Substring(0, dot);
    }

    /// <summary>"VFX.CameraShake" → "CameraShake"</summary>
    private static string LastSegment(string typeId)
    {
        var dot = typeId.LastIndexOf('.');
        return dot < 0 ? typeId : typeId.Substring(dot + 1);
    }

    // ── 类型映射 ─────────────────────────────────────────────

    private static string PortTypeToCSharp(string dslType)
    {
        return dslType.ToLower() switch
        {
            "float"    => "float",
            "int"      => "int",
            "bool"     => "bool",
            "string"   => "string",
            "sceneref" => "string", // 场景绑定存储为 marker ID 字符串
            "list"     => "string", // StructList 存储为 JSON 字符串
            _          => "string",
        };
    }

    /// <summary>FieldDecl.TypeName → C# 类型（PropertyKey 泛型参数）</summary>
    private static string FieldTypeToCSharp(string dslType)
    {
        return dslType.ToLower() switch
        {
            "float"    => "float",
            "int"      => "int",
            "bool"     => "bool",
            "string"   => "string",
            "enum"            => "string", // 枚举属性序列化为字符串
            "sceneref"        => "string", // 场景绑定存储为 marker ID 字符串
            "list"            => "string", // StructList 存储为 JSON 字符串
            "signaltag"       => "string", // 信号标签选择器存储为路径字符串
            "entityref"       => "string", // 实体引用选择器存储为 Mode:Value 字符串
            "conditionparams" => "string", // 条件参数存储为 key=value;... 字符串
            _                 => "string",
        };
    }

    // ── 值格式化 ─────────────────────────────────────────────

    private static string FormatFloat(string s)
    {
        if (float.TryParse(s, NumberStyles.Float, CultureInfo.InvariantCulture, out var v))
            return v.ToString("G", CultureInfo.InvariantCulture) + "f";
        return "0f";
    }

    private static string FormatInt(string s)
    {
        if (int.TryParse(s, out var v)) return v.ToString();
        return "0";
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    // ── 元数据解析 ───────────────────────────────────────────

    /// <summary>"0.2 0.6 1.0" → "0.2f, 0.6f, 1.0f"</summary>
    private static string? ParseThemeColor(string raw)
    {
        var parts = raw.Split(' ');
        if (parts.Length < 3) return null;
        return $"{FormatFloat(parts[0])}, {FormatFloat(parts[1])}, {FormatFloat(parts[2])}";
    }

    /// <summary>"instant" → "ActionDuration.Instant"</summary>
    private static string ParseDuration(string? raw)
    {
        return (raw?.ToLower()) switch
        {
            "duration" => "ActionDuration.Duration",
            "passive"  => "ActionDuration.Passive",
            _          => "ActionDuration.Instant",
        };
    }

    /// <summary>
    /// 将 sceneref 类型参数解析为 BindingType 枚举值。
    /// <para>
    /// sceneref(T) 中 T 可能是基类类型（Area/Point/Transform/Path/Collider）或
    /// 具体子类型（WaveSpawnArea/TriggerZone 等）。
    /// 通过 markerBaseTypeRegistry 查找子类型的基类，再映射为 BindingType 枚举值。
    /// </para>
    /// </summary>
    private static string ResolveBindingType(string markerTypeId, Dictionary<string, string>? markerBaseTypeRegistry)
    {
        // 已知的 BindingType 枚举值（直接匹配）
        var knownBindingTypes = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
            { "Transform", "Area", "Path", "Collider" };

        if (knownBindingTypes.Contains(markerTypeId))
            return markerTypeId; // 直接就是枚举值（如 sceneref(Area)）

        // 查注册表：具体子类型 → 基类
        if (markerBaseTypeRegistry != null && markerBaseTypeRegistry.TryGetValue(markerTypeId, out var baseType))
        {
            // 基类也可能不是 BindingType 枚举值（如 Point → Transform）
            return MapBaseTypeToBindingType(baseType);
        }

        // 无注册表信息，尝试按名称猜测
        return MapBaseTypeToBindingType(markerTypeId);
    }

    /// <summary>将 Marker 基类名称映射为 BindingType 枚举值</summary>
    private static string MapBaseTypeToBindingType(string baseType)
    {
        return baseType.ToLower() switch
        {
            "area"      => "Area",
            "point"     => "Transform",
            "transform" => "Transform",
            "path"      => "Path",
            "collider"  => "Collider",
            _           => "Transform", // 兜底默认
        };
    }
}
