#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SbdefGen.Core.Ast;

namespace SbdefGen.Core.Emitters;

/// <summary>
/// v0.3 Emitter：从 SbdefFile 中的 MarkerDecl 生成 C# 代码。
/// <list type="bullet">
/// <item>UMarkerTypeIds.cs            — 类型 ID 字符串常量（Runtime）</item>
/// <item>Markers/{Name}Marker.cs      — 每个 Marker 独立文件（Runtime MonoBehaviour）</item>
/// <item>UMarkerDefs.cs              — IMarkerDefinitionProvider 实现（Editor-only）</item>
/// </list>
/// </summary>
internal static class SbdefMarkerEmitter
{
    /// <returns>
    /// 字典键以 "Editor/" 前缀开头的条目输出到 Generated/Editor/，
    /// 以 "Markers/" 前缀开头的条目输出到 Generated/Markers/（每个 Marker 独立文件）。
    /// </returns>
    public static Dictionary<string, string> Emit(SbdefFile ast, string sourceName)
    {
        var markers = ast.Statements.OfType<MarkerDecl>().ToList();
        if (markers.Count == 0)
            return new Dictionary<string, string>();

        var pascal = CapFirst(sourceName);
        var result = new Dictionary<string, string>
        {
            [$"UMarkerTypeIds.{pascal}.cs"]     = EmitTypeIds(markers, sourceName),
            [$"Editor/UMarkerDefs.{pascal}.cs"] = EmitMarkerDefs(markers, sourceName),
        };

        // 每个 Marker 生成独立 .cs 文件（文件名 = 类名，Unity MonoBehaviour 要求）
        foreach (var m in markers)
        {
            var className = m.Name + "Marker";
            result[$"Markers/{className}.cs"] = EmitSingleMarker(m, sourceName);
        }

        return result;
    }

    private static string CapFirst(string s)
        => string.IsNullOrEmpty(s) ? s : char.ToUpper(s[0]) + s.Substring(1);

    // ── UMarkerTypeIds 生成 ──────────────────────────────────

    private static string EmitTypeIds(List<MarkerDecl> markers, string sourceName)
    {
        var members = string.Join("\n", markers.Select(m =>
        {
            var label = m.Label ?? m.Name;
            return $"        /// <summary>{label}</summary>\n        public const string {m.Name} = \"{m.Name}\";";
        }));

        return $$"""
// <auto-generated>
// 由 SbdefCodegen 从 {{sourceName}}.sbdef 生成，请勿手动修改。
// </auto-generated>
#nullable enable

namespace SceneBlueprintUser.Generated
{
    public static partial class UMarkerTypeIds
    {
{{members}}
    }
}

""";
    }

    // ── 单个 Marker 独立文件生成 ─────────────────────────────

    private static string EmitSingleMarker(MarkerDecl m, string sourceName)
    {
        var className = m.Name + "Marker";
        var baseClass = m.BaseType != null ? $"{m.BaseType}Marker" : "SceneMarker";

        // 可选 gizmo 注释
        var gizmoComment = !string.IsNullOrEmpty(m.GizmoShape)
            ? $"        // gizmo: {m.GizmoShape}{(m.GizmoParam != null ? $"({m.GizmoParam})" : "")}  — 在对应的 Editor Gizmo Drawer 中实现\n"
            : "";

        // 可选的自动添加 Annotation 代码
        var autoAnnotations = BuildAutoAnnotationLines(m);

        return $$"""
// <auto-generated>
// 由 SbdefCodegen 从 {{sourceName}}.sbdef 生成，请勿手动修改。
// 手写业务字段请在对应的 partial 文件中扩展，勿修改此文件。
// </auto-generated>
#nullable enable
using UnityEngine;
using SceneBlueprint.Runtime.Markers;

namespace SceneBlueprintUser.Generated
{
    public class {{className}} : {{baseClass}}
    {
        public override string MarkerTypeId => UMarkerTypeIds.{{m.Name}};
{{gizmoComment}}
#if UNITY_EDITOR
        protected override void Reset()
        {
            base.Reset();
            if (string.IsNullOrEmpty(MarkerId))
                MarkerId = System.Guid.NewGuid().ToString("N").Substring(0, 12);
{{autoAnnotations}}        }
#endif
    }
}

""";
    }

    /// <summary>生成 Reset() 中自动添加 Annotation 的代码行</summary>
    private static string BuildAutoAnnotationLines(MarkerDecl m)
    {
        var sb = new StringBuilder();

        // 阶段4：声明式关联 use_annotations
        if (m.UsedAnnotations != null && m.UsedAnnotations.Count > 0)
        {
            foreach (var annotationName in m.UsedAnnotations)
            {
                var cls = $"SceneBlueprintUser.Annotations.{annotationName}Annotation";
                sb.AppendLine($"            // 自动添加 {annotationName}");
                sb.AppendLine($"            if (GetComponent<{cls}>() == null)");
                sb.AppendLine($"                gameObject.AddComponent<{cls}>();");
            }
        }
        // 阶段3：嵌套式 Annotation（兼容旧代码）
        else if (m.Annotations != null && m.Annotations.Count > 0)
        {
            foreach (var annotation in m.Annotations)
            {
                var cls = $"SceneBlueprintUser.Annotations.{annotation.Name}Annotation";
                sb.AppendLine($"            // 自动添加 {annotation.DisplayName ?? annotation.Name}");
                sb.AppendLine($"            if (GetComponent<{cls}>() == null)");
                sb.AppendLine($"                gameObject.AddComponent<{cls}>();");
            }
        }

        return sb.ToString();
    }

    // ── UMarkerDefs（IMarkerDefinitionProvider）生成 ────────

    private static string EmitMarkerDefs(List<MarkerDecl> markers, string sourceName)
    {
        var sb = new StringBuilder();
        foreach (var m in markers)
        {
            var className   = m.Name + "Marker";
            var defClass    = m.Name + "MarkerDef";
            var displayName = m.Label ?? m.Name;
            var groupLine   = !string.IsNullOrEmpty(m.Group)
                ? $"\n            Group         = \"{EscapeString(m.Group)}\","
                : "";

            sb.AppendLine($"    [MarkerDef(UMarkerTypeIds.{m.Name})]");
            sb.AppendLine($"    public class {defClass} : IMarkerDefinitionProvider");
            sb.AppendLine( "    {");
            sb.AppendLine( "        public MarkerDefinition Define() => new MarkerDefinition");
            sb.AppendLine( "        {");
            sb.AppendLine($"            TypeId        = UMarkerTypeIds.{m.Name},");
            sb.AppendLine($"            DisplayName   = \"{EscapeString(displayName)}\",");
            sb.AppendLine($"            ComponentType = typeof({className}),");
            sb.Append    ( "            DefaultSpacing = 2f,");
            sb.AppendLine(groupLine);
            sb.AppendLine( "        };");
            sb.AppendLine( "    }");
            sb.AppendLine();
        }

        var defs = sb.ToString();
        return $$"""
// <auto-generated>
// 由 SbdefCodegen 从 {{sourceName}}.sbdef 生成，请勿手动修改。
// </auto-generated>
#nullable enable
using SceneBlueprint.Editor.Markers.Definitions;
using SceneBlueprint.Runtime.Markers;
using SceneBlueprintUser.Generated;

namespace SceneBlueprintUser.Generated.Editor
{
{{defs}}}

""";
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
