#nullable enable
using System.Collections.Generic;
using System.Text;
using SbdefGen.Core;
using SbdefGen.Core.Ast;

namespace SbdefGen.Core.Emitters;

/// <summary>
/// .sbdef EditorTool 代码生成器 — 从 editor_tool 块生成 IMarkerEditorExtension 实现类。
/// <para>
/// 生成产物：
/// - Editor/EditorTools/{ToolName}.cs — Editor Tool 类（partial，UI 代码由开发者补充）
/// </para>
/// </summary>
internal static class SbdefEditorToolEmitter
{
    public static Dictionary<string, string> Emit(SbdefFile ast, string sourceName)
    {
        var output = new Dictionary<string, string>();

        foreach (var stmt in ast.Statements)
        {
            if (stmt is MarkerDecl marker && marker.EditorTools != null)
            {
                foreach (var tool in marker.EditorTools)
                {
                    var toolCode = GenerateEditorToolClass(tool, marker.Name);
                    output[$"Editor/EditorTools/{tool.Name}.cs"] = toolCode;
                }
            }
        }

        return output;
    }

    private static string GenerateEditorToolClass(EditorToolDecl tool, string markerName)
    {
        var displayName = tool.DisplayName ?? tool.Name;

        // 动态部分：参数字段 + 枚举定义
        var dynamicSb = new StringBuilder();
        foreach (var param in tool.Parameters)
            GenerateToolParameter(dynamicSb, param);
        foreach (var param in tool.Parameters)
        {
            if (param.TypeName == "enum" && param.EnumValues != null)
            {
                dynamicSb.AppendLine();
                GenerateEnumDefinition(dynamicSb, param);
            }
        }
        var dynamicMembers = dynamicSb.ToString();

        return $$"""
// <auto-generated>
// 由 SbdefCodegen 生成，UI 代码请在 partial 类中补充。
// </auto-generated>
#nullable enable
using UnityEngine;
using UnityEditor;
using SceneBlueprint.Runtime.Markers;
using SceneBlueprint.Editor.Markers.Extensions;

namespace SceneBlueprintUser.Editor.EditorTools
{
    [MarkerEditorExtension("{{markerName}}")]
    public partial class {{tool.Name}}
        : IMarkerEditorExtension
    {
        public string TargetMarkerTypeId => "{{markerName}}";
        public string DisplayName => "{{displayName}}";

        // 工具状态字段
        private bool _foldout;
{{dynamicMembers}}
        // UI 绘制方法（由开发者在 partial 类中实现）
        partial void DrawToolUI(SceneMarker marker);

        public void DrawInspectorGUI(SceneMarker marker)
        {
            _foldout = EditorGUILayout.BeginFoldoutHeaderGroup(_foldout, "🔧 " + DisplayName);
            if (_foldout)
            {
                EditorGUI.indentLevel++;
                DrawToolUI(marker);
                EditorGUI.indentLevel--;
            }
            EditorGUILayout.EndFoldoutHeaderGroup();
        }
    }
}

""";
    }

    private static void GenerateToolParameter(StringBuilder sb, ToolParameterDecl param)
    {
        var csType = MapParameterType(param);
        var defaultValue = GetParameterDefaultValue(param);
        var fieldName = "_" + SbdefNameUtility.ToCamel(param.Name);
        
        sb.AppendLine($"        private {csType} {fieldName} = {defaultValue};");
    }

    private static void GenerateEnumDefinition(StringBuilder sb, ToolParameterDecl param)
    {
        if (param.EnumValues == null || param.EnumValues.Count == 0) return;
        
        var enumName = SbdefNameUtility.ToPascal(param.Name);
        sb.AppendLine($"        public enum {enumName}");
        sb.AppendLine("        {");
        for (int i = 0; i < param.EnumValues.Count; i++)
        {
            var comma = i < param.EnumValues.Count - 1 ? "," : "";
            sb.AppendLine($"            {param.EnumValues[i]}{comma}");
        }
        sb.AppendLine("        }");
    }

    private static string MapParameterType(ToolParameterDecl param)
    {
        if (param.TypeName == "enum")
        {
            return SbdefNameUtility.ToPascal(param.Name);
        }
        
        return param.TypeName switch
        {
            "int" => "int",
            "float" => "float",
            "bool" => "bool",
            "string" => "string",
            _ => "object"
        };
    }

    private static string GetParameterDefaultValue(ToolParameterDecl param)
    {
        if (!string.IsNullOrEmpty(param.DefaultValue))
        {
            if (param.TypeName == "string")
                return $"\"{param.DefaultValue}\"";
            if (param.TypeName == "float" && !param.DefaultValue.EndsWith("f"))
                return param.DefaultValue + "f";
            if (param.TypeName == "enum" && param.EnumValues != null && param.EnumValues.Count > 0)
                return $"{SbdefNameUtility.ToPascal(param.Name)}.{param.EnumValues[0]}";
            return param.DefaultValue;
        }

        return param.TypeName switch
        {
            "int" => "0",
            "float" => "0f",
            "bool" => "false",
            "string" => "\"\"",
            "enum" => param.EnumValues != null && param.EnumValues.Count > 0 
                ? $"{SbdefNameUtility.ToPascal(param.Name)}.{param.EnumValues[0]}" 
                : "0",
            _ => "default!"
        };
    }
}
