#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SbdefGen.Core;
using SbdefGen.Core.Ast;

namespace SbdefGen.Core.Emitters;

/// <summary>
/// 将 SbdefFile 中的 SignalDecl 节点生成两份 C# 代码：
/// <list type="bullet">
/// <item>USignalTags.{Name}.cs — 信号标签常量（SignalTag 路径字符串）</item>
/// <item>USignalPayloads.{Name}.cs — 信号载荷工厂类（带参数的 signal 生成 Create 方法）</item>
/// </list>
/// </summary>
internal static class SbdefSignalEmitter
{
    public static Dictionary<string, string> Emit(SbdefFile ast, string sourceName)
    {
        var signals = ast.Statements.OfType<SignalDecl>().ToList();
        if (signals.Count == 0)
            return new Dictionary<string, string>();

        var result = new Dictionary<string, string>();

        // 按第一段分组（如 Combat / Spawn / Phase）
        var groups = signals
            .GroupBy(s => FirstSegment(s.TagPath))
            .ToList();

        foreach (var grp in groups)
        {
            var ns = grp.Key;
            var pascal = SbdefActionEmitter.ToPascalSegment(ns);

            result[$"USignalTags.{pascal}.cs"] = EmitSignalTags(grp.ToList(), pascal, sourceName);

            // 只有存在带参数的 signal 时才生成 Payloads 工厂
            var withParams = grp.Where(s => s.Params is { Count: > 0 }).ToList();
            if (withParams.Count > 0)
                result[$"USignalPayloads.{pascal}.cs"] = EmitSignalPayloads(withParams, pascal, sourceName);
        }

        return result;
    }

    // ── USignalTags 生成 ─────────────────────────────────────────

    private static string EmitSignalTags(List<SignalDecl> signals, string nestedClass, string sourceName)
    {
        var sb = new StringBuilder();
        foreach (var s in signals)
        {
            var constName = TagPathToConstName(s.TagPath);
            if (!string.IsNullOrEmpty(s.Label))
                sb.AppendLine($"            /// <summary>{s.Label}</summary>");
            sb.AppendLine($"            public const string {constName} = \"{s.TagPath}\";");
        }

        return $$"""
// <auto-generated>
// 由 SbdefCodegen 从 {{sourceName}}.sbdef 生成，请勿手动修改。
// </auto-generated>
#nullable enable

namespace SceneBlueprintUser.Generated
{
    /// <summary>信号标签常量（自动生成）</summary>
    public static partial class USignalTags
    {
        public static class {{nestedClass}}
        {
{{sb.ToString().TrimEnd()}}
        }
    }
}

""";
    }

    // ── USignalPayloads 生成 ─────────────────────────────────────

    private static string EmitSignalPayloads(List<SignalDecl> signals, string nestedClass, string sourceName)
    {
        var sb = new StringBuilder();
        foreach (var s in signals)
        {
            var methodName = TagPathToConstName(s.TagPath);
            var paramList = string.Join(", ", s.Params!.Select(p => $"{MapCsType(p.TypeName)} {SbdefNameUtility.ToCamel(p.Name)}"));
            
            sb.AppendLine($"            /// <summary>创建 {s.TagPath} 信号载荷</summary>");
            sb.AppendLine($"            public static SceneBlueprint.Contract.SignalPayload {methodName}({paramList})");
            sb.AppendLine( "            {");
            sb.AppendLine( "                var payload = new SceneBlueprint.Contract.SignalPayload();");
            foreach (var p in s.Params!)
            {
                var accessor = SbdefNameUtility.ToCamel(p.Name);
                sb.AppendLine($"                payload[\"{p.Name}\"] = {accessor}.ToString();");
            }
            sb.AppendLine( "                return payload;");
            sb.AppendLine( "            }");
            sb.AppendLine();
        }

        return $$"""
// <auto-generated>
// 由 SbdefCodegen 从 {{sourceName}}.sbdef 生成，请勿手动修改。
// </auto-generated>
#nullable enable

namespace SceneBlueprintUser.Generated
{
    /// <summary>信号载荷工厂类（自动生成）</summary>
    public static partial class USignalPayloads
    {
        public static class {{nestedClass}}
        {
{{sb.ToString().TrimEnd()}}
        }
    }
}

""";
    }

    // ── 工具方法 ─────────────────────────────────────────────────

    /// <summary>"Combat.Monster.Died" → "Combat"</summary>
    private static string FirstSegment(string tagPath)
    {
        var dot = tagPath.IndexOf('.');
        return dot < 0 ? tagPath : tagPath.Substring(0, dot);
    }

    /// <summary>
    /// "Combat.Monster.Died" → "MonsterDied"（跳过第一段，拼接后续段为 PascalCase）
    /// "Phase.Started" → "Started"
    /// </summary>
    private static string TagPathToConstName(string tagPath)
    {
        var parts = tagPath.Split('.');
        if (parts.Length <= 1) return tagPath;
        return string.Join("", parts.Skip(1));
    }

    private static string MapCsType(string typeName) => typeName switch
    {
        "string" => "string",
        "int"    => "int",
        "float"  => "float",
        "bool"   => "bool",
        _        => "string"
    };

}
