#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SbdefGen.Core.Ast;

namespace SbdefGen.Core.Emitters;

/// <summary>
/// 将 SbdefFile 中的 TagDimensionDecl 节点生成两份 C# 代码：
/// <list type="bullet">
/// <item>UTagDimensions.cs — Tag 路径常量（嵌套类按维度分组）</item>
/// <item>TagDimensionDefs.cs — 维度元数据注册（ITagDimensionDefinitionProvider 实现）</item>
/// </list>
/// </summary>
internal static class SbdefTagDimensionEmitter
{
    public static Dictionary<string, string> Emit(SbdefFile ast, string sourceName)
    {
        var dimensions = ast.Statements.OfType<TagDimensionDecl>().ToList();
        if (dimensions.Count == 0)
            return new Dictionary<string, string>();

        var result = new Dictionary<string, string>
        {
            [$"UTagDimensions.{sourceName}.cs"] = EmitTagDimensionConstants(dimensions, sourceName),
            [$"TagDimensionDefs.{sourceName}.cs"] = EmitTagDimensionDefs(dimensions, sourceName)
        };

        return result;
    }

    // ── UTagDimensions 生成 ─────────────────────────────────────────

    private static string EmitTagDimensionConstants(List<TagDimensionDecl> dimensions, string sourceName)
    {
        var sb = new StringBuilder();
        for (int d = 0; d < dimensions.Count; d++)
        {
            var dim = dimensions[d];
            if (d > 0) sb.AppendLine();

            if (!string.IsNullOrEmpty(dim.DisplayName))
                sb.AppendLine($"        /// <summary>{dim.DisplayName}（{(dim.IsExclusive ? "exclusive" : "multiple")}）</summary>");
            sb.AppendLine($"        public static class {dim.Name}");
            sb.AppendLine( "        {");
            sb.AppendLine($"            /// <summary>维度前缀</summary>");
            sb.AppendLine($"            public const string Prefix = \"{dim.Name}\";");

            foreach (var val in dim.Values)
            {
                if (!string.IsNullOrEmpty(val.Label))
                    sb.AppendLine($"            /// <summary>{val.Label}</summary>");
                sb.AppendLine($"            public const string {val.Name} = \"{dim.Name}.{val.Name}\";");
            }
            sb.AppendLine( "        }");
        }

        return $$"""
// <auto-generated>
// 由 SbdefCodegen 从 {{sourceName}}.sbdef 生成，请勿手动修改。
// </auto-generated>
#nullable enable

namespace SceneBlueprintUser.Generated
{
    /// <summary>Tag 维度路径常量（自动生成）</summary>
    public static partial class UTagDimensions
    {
{{sb.ToString().TrimEnd()}}
    }
}

""";
    }

    // ── TagDimensionDefs 生成 ───────────────────────────────────────

    private static string EmitTagDimensionDefs(List<TagDimensionDecl> dimensions, string sourceName)
    {
        var providerClass = $"TagDimensionDefs_{ToPascalCase(sourceName)}";
        var sb = new StringBuilder();

        for (int d = 0; d < dimensions.Count; d++)
        {
            var dim = dimensions[d];
            if (d > 0) sb.AppendLine();

            sb.AppendLine( "                new SceneBlueprint.Core.TagDimensionDef");
            sb.AppendLine( "                {");
            sb.AppendLine($"                    Id = \"{dim.Name}\",");
            sb.AppendLine($"                    DisplayName = \"{EscapeString(dim.DisplayName ?? dim.Name)}\",");
            sb.AppendLine($"                    IsExclusive = {(dim.IsExclusive ? "true" : "false")},");
            sb.AppendLine($"                    Order = {d},");
            sb.AppendLine( "                    Values = new SceneBlueprint.Core.TagValueDef[]");
            sb.AppendLine( "                    {");

            foreach (var val in dim.Values)
            {
                sb.AppendLine($"                        new SceneBlueprint.Core.TagValueDef {{ Name = \"{val.Name}\", Label = \"{EscapeString(val.Label ?? val.Name)}\", FullPath = \"{dim.Name}.{val.Name}\" }},");
            }

            sb.AppendLine( "                    }");
            sb.AppendLine( "                },");
        }

        return $$"""
// <auto-generated>
// 由 SbdefCodegen 从 {{sourceName}}.sbdef 生成，请勿手动修改。
// </auto-generated>
#nullable enable

namespace SceneBlueprintUser.Generated
{
    /// <summary>Tag 维度元数据定义（自动生成）</summary>
    public class {{providerClass}} : SceneBlueprint.Core.ITagDimensionDefinitionProvider
    {
        public SceneBlueprint.Core.TagDimensionDef[] Define() => new SceneBlueprint.Core.TagDimensionDef[]
        {
{{sb.ToString().TrimEnd()}}
        };
    }
}

""";
    }

    // ── 工具方法 ─────────────────────────────────────────────────

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToUpper(name[0]) + name.Substring(1);
    }

    private static string EscapeString(string s)
    {
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
