#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using SceneBlueprint.Core;
using UnityEditor;
using UnityEngine;

namespace SceneBlueprint.Editor
{
    /// <summary>
    /// P3 代码生成器——扫描所有 IActionDefinitionProvider，
    /// 自动生成 Core/Generated/ActionPortIds.cs。
    /// <para>
    /// 生成的文件将所有 Action 的端口 ID 和属性 Key 集中到 Core 层，
    /// 供 Runtime 和其他不依赖 Actions 程序集的代码使用。
    /// </para>
    /// <para>
    /// 调用方式：菜单 SceneBlueprint → 生成 ActionPortIds.cs。
    /// 也可在 ActionRegistry 内容变化后手动触发，或接入 CI 流程。
    /// </para>
    /// </summary>
    public static class ActionPortIdsGenerator
    {
        private const string OutputPath =
            "Assets/SceneBlueprintData/Generated/ActionPortIds.cs";

        [MenuItem("SceneBlueprint/生成 ActionPortIds.cs (P3)")]
        public static void Generate()
        {
            var registry = SceneBlueprintProfile.CreateActionRegistry();
            var definitions = registry.GetAll().ToList();

            if (definitions.Count == 0)
            {
                UnityEngine.Debug.LogWarning("[ActionPortIdsGenerator] ActionRegistry 为空，未生成文件。");
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// 此文件由 ActionPortIdsGenerator 自动生成，请勿手动修改。");
            sb.AppendLine($"// 生成时间：{DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine("// 调用方式：菜单 SceneBlueprint → 生成 ActionPortIds.cs (P3)");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace SceneBlueprint.Core.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 所有内置 Action 端口 ID 与属性 Key 的编译时常量（自动生成）。");
            sb.AppendLine("    /// <para>");
            sb.AppendLine("    /// 与 <see cref=\"AT\"/> 配合使用，确保 System 层不包含任何魔法字符串：");
            sb.AppendLine("    /// <code>");
            sb.AppendLine("    /// frame.SetDataPortValue(idx, ActionPortIds.SpawnWave.WaveIndex, value);");
            sb.AppendLine("    /// </code>");
            sb.AppendLine("    /// </para>");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class ActionPortIds");
            sb.AppendLine("    {");

            foreach (var def in definitions.OrderBy(d => d.TypeId))
            {
                // 将 TypeId 转为合法 C# 类名（"Spawn.Wave" → "SpawnWave"）
                var className = TypeIdToClassName(def.TypeId);
                sb.AppendLine($"        /// <summary>{EscapeXml(def.DisplayName ?? def.TypeId)} ({def.TypeId})</summary>");
                sb.AppendLine($"        public static class {className}");
                sb.AppendLine("        {");

                if (def.Ports != null && def.Ports.Length > 0)
                {
                    sb.AppendLine("            // 端口 ID");
                    foreach (var port in def.Ports)
                    {
                        var constName = ToCamelCase(port.Id);
                        sb.AppendLine($"            public const string {constName} = \"{port.Id}\";");
                    }
                }

                if (def.Properties != null && def.Properties.Length > 0)
                {
                    if (def.Ports != null && def.Ports.Length > 0)
                        sb.AppendLine();
                    sb.AppendLine("            // 属性 Key");
                    foreach (var prop in def.Properties)
                    {
                        var constName = ToCamelCase(prop.Key);
                        sb.AppendLine($"            public const string {constName} = \"{prop.Key}\";");
                    }
                }

                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            // 确保目录存在
            var fullPath = Path.Combine(Application.dataPath, "..", OutputPath);
            var dir = Path.GetDirectoryName(fullPath)!;
            if (!Directory.Exists(dir)) Directory.CreateDirectory(dir);

            File.WriteAllText(fullPath, sb.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();

            UnityEngine.Debug.Log($"[ActionPortIdsGenerator] 已生成 {OutputPath}（{definitions.Count} 个 Action）");
        }

        // ── 辅助方法 ──

        /// <summary>"Flow.Filter" → "FlowFilter"，"Spawn.Wave" → "SpawnWave"</summary>
        private static string TypeIdToClassName(string typeId)
        {
            var parts = typeId.Split('.');
            return string.Concat(parts.Select(p =>
                p.Length > 0 ? char.ToUpper(p[0]) + p.Substring(1) : p));
        }

        /// <summary>"compareValue" → "CompareValue"，"in" → "In"</summary>
        private static string ToCamelCase(string id)
        {
            if (string.IsNullOrEmpty(id)) return id;
            // 首字母大写
            return char.ToUpper(id[0]) + id.Substring(1);
        }

        private static string EscapeXml(string s) =>
            s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
