#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SceneBlueprint.Editor.CodeGen.Sbdef
{
    /// <summary>
    /// v0.3 Emitter：从 SbdefFile 中的 MarkerDecl 生成三份 C# 代码。
    /// <list type="bullet">
    /// <item>UMarkerTypeIds.g.cs   — 类型 ID 字符串常量（Runtime）</item>
    /// <item>UMarkers.g.cs         — SceneMarker partial 骨架（Runtime）</item>
    /// <item>UMarkerDefs.g.cs      — IMarkerDefinitionProvider 实现（Editor-only）</item>
    /// </list>
    /// </summary>
    internal static class SbdefMarkerEmitter
    {
        /// <returns>
        /// 字典键以 "Editor/" 前缀开头的条目需输出到 Generated/Editor/ 子目录。
        /// </returns>
        public static Dictionary<string, string> Emit(SbdefFile ast, string sourceName)
        {
            var markers = ast.Statements.OfType<MarkerDecl>().ToList();
            if (markers.Count == 0)
                return new Dictionary<string, string>();

            // sourceName 用于区分多个 .sbdef 文件，避免文件名冲突
            // UMarkerTypeIds 用 partial class 合并，UMarkers/UMarkerDefs 各自独立
            var pascal = CapFirst(sourceName); // e.g. "markers" → "Markers"
            var result = new Dictionary<string, string>
            {
                [$"UMarkerTypeIds.{pascal}.g.cs"]       = EmitTypeIds(markers, sourceName),
                [$"UMarkers.{pascal}.g.cs"]             = EmitMarkers(markers, sourceName),
                [$"Editor/UMarkerDefs.{pascal}.g.cs"]   = EmitMarkerDefs(markers, sourceName),
            };
            return result;
        }

        private static string CapFirst(string s)
            => string.IsNullOrEmpty(s) ? s : char.ToUpper(s[0]) + s.Substring(1);

        // ── UMarkerTypeIds 生成 ──────────────────────────────────

        private static string EmitTypeIds(List<MarkerDecl> markers, string sourceName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// 由 SbdefCodegen 从 {sourceName}.sbdef 生成，请勿手动修改。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace SceneBlueprintUser.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class UMarkerTypeIds");
            sb.AppendLine("    {");

            foreach (var m in markers)
            {
                var label = m.Label ?? m.Name;
                sb.AppendLine($"        /// <summary>{label}</summary>");
                sb.AppendLine($"        public const string {m.Name} = \"{m.Name}\";");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ── UMarkers（SceneMarker partial 骨架）生成 ────────────

        private static string EmitMarkers(List<MarkerDecl> markers, string sourceName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// 由 SbdefCodegen 从 {sourceName}.sbdef 生成，请勿手动修改。");
            sb.AppendLine("// 手写业务字段请在对应的 partial 文件中扩展，勿修改此文件。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using SceneBlueprint.Runtime.Markers;");
            sb.AppendLine();
            sb.AppendLine("namespace SceneBlueprintUser.Generated");
            sb.AppendLine("{");

            foreach (var m in markers)
            {
                var className = m.Name + "Marker";
                sb.AppendLine($"    [AddComponentMenu(\"SceneBlueprintUser/{m.Name} Marker\")]");
                sb.AppendLine($"    public partial class {className} : SceneMarker");
                sb.AppendLine("    {");
                sb.AppendLine($"        public override string MarkerTypeId => UMarkerTypeIds.{m.Name};");

                // 若 DSL 声明了 gizmo 形状，生成提示注释（实际渲染由 Editor Gizmo Drawer 负责）
                if (!string.IsNullOrEmpty(m.GizmoShape))
                {
                    var param = m.GizmoParam != null ? $"({m.GizmoParam})" : "";
                    sb.AppendLine($"        // gizmo: {m.GizmoShape}{param}  — 在对应的 Editor Gizmo Drawer 中实现");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        // ── UMarkerDefs（IMarkerDefinitionProvider）生成 ────────

        private static string EmitMarkerDefs(List<MarkerDecl> markers, string sourceName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// 由 SbdefCodegen 从 {sourceName}.sbdef 生成，请勿手动修改。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using SceneBlueprint.Editor.Markers.Definitions;");
            sb.AppendLine("using SceneBlueprint.Runtime.Markers;");
            sb.AppendLine("using SceneBlueprintUser.Generated;");
            sb.AppendLine();
            sb.AppendLine("namespace SceneBlueprintUser.Generated.Editor");
            sb.AppendLine("{");

            foreach (var m in markers)
            {
                var className   = m.Name + "Marker";
                var defClass    = m.Name + "MarkerDef";
                var displayName = m.Label ?? m.Name;

                sb.AppendLine($"    [MarkerDef(UMarkerTypeIds.{m.Name})]");
                sb.AppendLine($"    public class {defClass} : IMarkerDefinitionProvider");
                sb.AppendLine("    {");
                sb.AppendLine("        public MarkerDefinition Define() => new MarkerDefinition");
                sb.AppendLine("        {");
                sb.AppendLine($"            TypeId        = UMarkerTypeIds.{m.Name},");
                sb.AppendLine($"            DisplayName   = \"{EscapeString(displayName)}\",");
                sb.AppendLine($"            ComponentType = typeof({className}),");
                sb.AppendLine("            DefaultSpacing = 2f,");
                sb.AppendLine("        };");
                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string EscapeString(string s)
            => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
