#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SceneBlueprint.Editor.CodeGen.Sbdef
{
    /// <summary>
    /// 将 SbdefFile 中的 ActionDecl 节点生成两份 C# 代码：
    /// <list type="bullet">
    /// <item>UAT.{Name}.g.cs — 用户层 Action TypeId 常量（生成到用户项目 Generated/）</item>
    /// </list>
    /// </summary>
    internal static class SbdefActionEmitter
    {
        /// <param name="ast">解析结果</param>
        /// <param name="sourceName">不含扩展名的 .sbdef 文件名，用于注释和类名后缀</param>
        /// <returns>键=文件名（含 .g.cs），值=文件内容</returns>
        public static Dictionary<string, string> Emit(SbdefFile ast, string sourceName)
        {
            var actions = ast.Statements.OfType<ActionDecl>().ToList();
            if (actions.Count == 0)
                return new Dictionary<string, string>();

            // 按 TypeId 的第一段分组，例如 "VFX" / "Spawn" / "Trigger"
            var groups = actions
                .GroupBy(a => FirstSegment(a.TypeId))
                .ToList();

            var result = new Dictionary<string, string>();

            foreach (var grp in groups)
            {
                var ns     = grp.Key;                // e.g. "VFX"
                var pascal = ToPascalSegment(ns);    // e.g. "Vfx"

                // v0.1: 只生成 UAT 类型 ID 常量（输出到用户项目 Generated/）
                // v0.2 计划: 添加 port 类型注解后生成 ActionPortIds（含 PropertyKey<T>）
                result[$"UAT.{pascal}.g.cs"] = EmitUAT(grp, pascal, sourceName);
            }

            return result;
        }

        // ── UAT 生成 ─────────────────────────────────────────────
        // UAT = User Action Types，生成到用户项目 Generated/，与框架 AT 隔离

        private static string EmitUAT(IEnumerable<ActionDecl> actions, string nestedClass, string sourceName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"// 由 SbdefCodegen 从 {sourceName}.sbdef 生成，请勿手动修改。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace SceneBlueprintUser.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class UAT");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static class {nestedClass}");
            sb.AppendLine("        {");

            foreach (var action in actions)
            {
                var constName = LastSegment(action.TypeId);
                sb.AppendLine($"            public const string {constName} = \"{action.TypeId}\";");
            }

            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        // ── 名称转换工具 ─────────────────────────────────────────
        // v0.2 计划：在此添加 EmitActionPortIds()，支持带类型注解的 port 生成 PropertyKey<T>

        /// <summary>"VFX.CameraShake" → "VFX"</summary>
        private static string FirstSegment(string typeId)
        {
            var dot = typeId.IndexOf('.');
            return dot < 0 ? typeId : typeId.Substring(0, dot);
        }

        /// <summary>"VFX.CameraShake" → "CameraShake"</summary>
        private static string LastSegment(string typeId)
        {
            var dot = typeId.LastIndexOf('.');
            return dot < 0 ? typeId : typeId.Substring(dot + 1);
        }

        /// <summary>
        /// 全大写缩写转 PascalCase 首字母大写其余小写，其他不变。
        /// "VFX" → "Vfx"，"AI" → "Ai"，"Spawn" → "Spawn"
        /// </summary>
        internal static string ToPascalSegment(string s)
        {
            if (string.IsNullOrEmpty(s)) return s;
            return s == s.ToUpperInvariant()
                ? char.ToUpper(s[0]) + s.Substring(1).ToLower()
                : s;
        }

    }
}
